function execute() {
    return Response.success([
        { title: "Truyện Mới Cập Nhật", input: "/", script: "home1.js" },
        { title: "Tất cả thể loại truyện tranh", input: "/", script: "home1.js" },
        { title: "Action", input: "/tim-truyen/action", script: "bot.js" },
        { title: "Adult", input: "/tim-truyen/truong-thanh", script: "bot.js" },
        { title: "Adventure", input: "/tim-truyen/phieu-luu", script: "bot.js" },
        { title: "Anime", input: "/tim-truyen/anime", script: "bot.js" },
        { title: "Chuyển Sinh", input: "/tim-truyen/chuyen-sinh", script: "bot.js" },
        { title: "Comedy", input: "/tim-truyen/comedy", script: "bot.js" },
        { title: "Cooking", input: "/tim-truyen/nau-an", script: "bot.js" },
        { title: "Comic", input: "/tim-truyen/comic", script: "bot.js" },
        { title: "Cổ Đại", input: "/tim-truyen/co-dai", script: "bot.js" },
        { title: "Drama", input: "/tim-truyen/drama", script: "bot.js" },
        { title: "Đam Mỹ", input: "/tim-truyen/dam-my", script: "bot.js" },
        { title: "Ecchi", input: "/tim-truyen/ecchi", script: "bot.js" },
        { title: "Fantasy", input: "/tim-truyen/fantasy", script: "bot.js" },
        { title: "Harem", input: "/tim-truyen/harem", script: "bot.js" },
        { title: "Historical", input: "/tim-truyen/historical", script: "bot.js" },
        { title: "Horror", input: "/tim-truyen/horror", script: "bot.js" },
        { title: "Live action", input: "/tim-truyen/live-action", script: "bot.js" },
        { title: "Manga", input: "/tim-truyen/manga", script: "bot.js" },
        { title: "Manhua", input: "/tim-truyen/manhua", script: "bot.js" },
        { title: "Manhwa", input: "/tim-truyen/manhwa", script: "bot.js" },
        { title: "Martial Arts", input: "/tim-truyen/martial-arts", script: "bot.js" },
        { title: "Mature", input: "/tim-truyen/mature", script: "bot.js" },
        { title: "Mystery", input: "/tim-truyen/mystery", script: "bot.js" },
        { title: "Mecha", input: "/tim-truyen/mecha", script: "bot.js" },
        { title: "Ngôn Tình", input: "/tim-truyen/ngon-tinh", script: "bot.js" },
        { title: "One shot", input: "/tim-truyen/one-shot", script: "bot.js" },
        { title: "Psychological", input: "/tim-truyen/psychological", script: "bot.js" },
        { title: "Romance", input: "/tim-truyen/romance", script: "bot.js" },
        { title: "School Life", input: "/tim-truyen/school-life", script: "bot.js" },
        { title: "Shoujo", input: "/tim-truyen/shoujo", script: "bot.js" },
        { title: "Shoujo Ai", input: "/tim-truyen/shoujo-ai", script: "bot.js" },
        { title: "Shounen", input: "/tim-truyen/shounen", script: "bot.js" },
        { title: "Slice of Life", input: "/tim-truyen/slice-of-life", script: "bot.js" },
        { title: "Seinen", input: "/tim-truyen/seinen", script: "bot.js" },
        { title: "Smut", input: "/tim-truyen/smut", script: "bot.js" },
        { title: "Sci-fi", input: "/tim-truyen/sci-fi", script: "bot.js" },
        { title: "Soft Yaoi", input: "/tim-truyen/soft-yaoi", script: "bot.js" },
        { title: "Soft Yuri", input: "/tim-truyen/soft-yuri", script: "bot.js" },
        { title: "Sports", input: "/tim-truyen/sports", script: "bot.js" },
        { title: "Supernatural", input: "/tim-truyen/supernatural", script: "bot.js" },
        { title: "Josei", input: "/tim-truyen/josei", script: "bot.js" },
        { title: "Thiếu Nhi", input: "/tim-truyen/thieu-nhi", script: "bot.js" },
        { title: "Trinh Thám", input: "/tim-truyen/trinh-tham", script: "bot.js" },
        { title: "Truyện Màu", input: "/tim-truyen/truyen-mau", script: "bot.js" },
        { title: "Tragedy", input: "/tim-truyen/tragedy", script: "bot.js" },
        { title: "Webtoon", input: "/tim-truyen/webtoon", script: "bot.js" },
        { title: "Xuyên Không", input: "/tim-truyen/xuyen-khong", script: "bot.js" },
        { title: "botder Bender", input: "/tim-truyen/botder-bender", script: "bot.js" },
        { title: "Yuri", input: "/tim-truyen/yuri", script: "bot.js" },
        { title: "Hệ Thống", input: "/tim-truyen/he-thong", script: "bot.js" },
        { title: "Yaoi", input: "/tim-truyen/yaoi", script: "bot.js" },
    ]);
}